# Generated by Django 5.2.8 on 2025-12-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0002_alter_candidateorm_github_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True,
                        help_text="Cover letter provided by the applicant",
                        null=True,
                        verbose_name="cover letter",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("offered", "Offered"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        help_text="Current status of the application",
                        max_length=20,
                        verbose_name="application status",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="The candidate who applied for the job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="candidates.candidateorm",
                        verbose_name="applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "job application",
                "verbose_name_plural": "job applications",
                "ordering": ["-created_at"],
            },
        ),
    ]
