# Generated by Django 5.2.8 on 2025-12-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationorm",
            name="post",
            field=models.ForeignKey(
                help_text="The job post this application is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.jobpostorm",
                verbose_name="job post",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="applicationorm",
            unique_together={("applicant", "post")},
        ),
    ]
