# Generated by Django 5.2.8 on 2025-12-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0003_remove_companyorm_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPostORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "title",
                    models.CharField(help_text="Title of the job position", max_length=255, verbose_name="job title"),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the job", verbose_name="job description"),
                ),
                (
                    "location",
                    models.CharField(help_text="Location of the job", max_length=255, verbose_name="job location"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("freelance", "Freelance"),
                        ],
                        default="full_time",
                        help_text="Type of employment for the job",
                        max_length=20,
                        verbose_name="employment type",
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum salary for the job",
                        max_digits=10,
                        null=True,
                        verbose_name="minimum salary",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum salary for the job",
                        max_digits=10,
                        null=True,
                        verbose_name="maximum salary",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this job post is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="companies.companyorm",
                        verbose_name="company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Post",
                "verbose_name_plural": "Job Posts",
                "ordering": ["-created_at"],
            },
        ),
    ]
