# Generated by Django 5.2.8 on 2025-11-30 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(db_index=True, help_text="Name of the company", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Description of the company", null=True)),
                ("website", models.URLField(blank=True, help_text="Website URL of the company", null=True)),
                ("logo", models.URLField(blank=True, help_text="Logo URL of the company", null=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this entity is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.companyorm",
                        verbose_name="company",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        help_text="The user who owns the company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_company",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ["-created_at"],
            },
        ),
    ]
