# Generated by Django 5.2.8 on 2025-12-01 06:22

import src.apps.shared.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyorm",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo image for the company",
                null=True,
                upload_to="companies/logos/%Y/%m/%d/",
                validators=[src.apps.shared.utils.validators.FileSizeValidator(max_size_mb=5)],
            ),
        ),
    ]
