# Generated by Django 5.2.8 on 2025-12-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_companyorm_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyorm",
            name="company",
        ),
    ]
