# Generated by Django 5.2.8 on 2025-11-30 17:26

import django.core.validators
import django.db.models.deletion
import src.apps.shared.models.fields
import src.apps.shared.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateORM",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="candidate_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Candidate's resume (PDF preferred, max 5MB)",
                        null=True,
                        upload_to="resumes/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=["pdf", "doc", "docx"]),
                            src.apps.shared.utils.validators.FileSizeValidator(max_size_mb=5),
                        ],
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, help_text="Default cover letter or personal statement", null=True),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Short professional bio (for public profile)", null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, State/Province, Country (e.g. Berlin, Germany)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "skills",
                    src.apps.shared.models.fields.CommaSeparatedCharField(
                        blank=True,
                        help_text="Comma-separated list of skills (e.g. Python, Django, React)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total years of professional experience", null=True
                    ),
                ),
                (
                    "current_title",
                    models.CharField(
                        blank=True, help_text="Current or most recent job title", max_length=150, null=True
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True, help_text="LinkedIn profile URL", null=True)),
                ("github_url", models.URLField(blank=True, help_text="GitHub profile URL", null=True)),
                ("portfolio_url", models.URLField(blank=True, help_text="Personal portfolio URL", null=True)),
                (
                    "is_open_to_work",
                    models.BooleanField(
                        default=True, help_text="Indicates if the candidate is open to new job opportunities"
                    ),
                ),
                (
                    "is_searching_actively",
                    models.BooleanField(
                        default=False, help_text="Indicates if the candidate is actively searching for a job"
                    ),
                ),
                (
                    "desired_salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Minimum desired salary", max_digits=10, null=True
                    ),
                ),
                (
                    "desired_salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Maximum desired salary", max_digits=10, null=True
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("UZS", "Uzbekistani Some"),
                            ("RUB", "Russian Ruble"),
                        ],
                        default="USD",
                        help_text="Currency for desired salary",
                        max_length=3,
                    ),
                ),
                (
                    "available_from",
                    models.DateField(blank=True, help_text="When the candidate can start working", null=True),
                ),
            ],
            options={
                "verbose_name": "candidate profile",
                "verbose_name_plural": "candidate profiles",
            },
        ),
    ]
