# Generated by Django 5.2.8 on 2025-12-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateorm",
            name="github_url",
            field=models.URLField(blank=True, help_text="GitHub profile URL", null=True, verbose_name="GitHub URL"),
        ),
        migrations.AlterField(
            model_name="candidateorm",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL", null=True, verbose_name="LinkedIn URL"),
        ),
        migrations.AlterField(
            model_name="candidateorm",
            name="portfolio_url",
            field=models.URLField(
                blank=True, help_text="Personal portfolio URL", null=True, verbose_name="Portfolio URL"
            ),
        ),
        migrations.AlterField(
            model_name="candidateorm",
            name="salary_currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("EUR", "Euro"), ("UZS", "Uzbekistani Sum"), ("RUB", "Russian Ruble")],
                default="USD",
                help_text="Currency for desired salary",
                max_length=3,
            ),
        ),
    ]
