# Generated by Django 5.2.8 on 2025-12-01 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("companies", "0003_remove_companyorm_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("completed", "Completed"), ("canceled", "Canceled")],
                        default="scheduled",
                        help_text="Current status of the interview",
                        max_length=20,
                        verbose_name="interview status",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="The date and time when the interview is scheduled", verbose_name="scheduled at"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="The location of the interview (if applicable)",
                        max_length=255,
                        null=True,
                        verbose_name="location",
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="The online meeting link for the interview (if applicable)",
                        null=True,
                        verbose_name="meeting link",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the interview", null=True, verbose_name="notes"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="The job application associated with this interview",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="applications.applicationorm",
                        verbose_name="application",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this entity is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.companyorm",
                        verbose_name="company",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user conducting the interview",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="interviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "interview",
                "verbose_name_plural": "interviews",
            },
        ),
    ]
