# Generated by Django 5.2.8 on 2025-12-02 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervieworm",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the interview is scheduled (set when slot is accepted)",
                null=True,
                verbose_name="scheduled at",
            ),
        ),
        migrations.AlterField(
            model_name="intervieworm",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="scheduled",
                help_text="Current status of the interview",
                max_length=20,
                verbose_name="interview status",
            ),
        ),
        migrations.CreateModel(
            name="InterviewSlotORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "start_time",
                    models.DateTimeField(help_text="Proposed interview start time", verbose_name="start time"),
                ),
                ("end_time", models.DateTimeField(help_text="Proposed interview end time", verbose_name="end time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed by Company"),
                            ("counter_proposed", "Counter-Proposed by Candidate"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        help_text="Status of this time slot proposal",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Interview location", max_length=255, null=True, verbose_name="location"
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="Online meeting link", null=True, verbose_name="meeting link"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this slot", null=True, verbose_name="notes"
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        help_text="The interview this slot is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="interviews.intervieworm",
                        verbose_name="interview",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        help_text="User who proposed this slot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="proposed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "interview slot",
                "verbose_name_plural": "interview slots",
                "ordering": ["-created_at"],
            },
        ),
    ]
