# Generated by Django 5.2.8 on 2025-12-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_alter_intervieworm_scheduled_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervieworm",
            name="interviewer",
        ),
        migrations.RemoveField(
            model_name="intervieworm",
            name="location",
        ),
        migrations.RemoveField(
            model_name="intervieworm",
            name="meeting_link",
        ),
        migrations.RemoveField(
            model_name="intervieworm",
            name="scheduled_at",
        ),
        migrations.AlterField(
            model_name="intervieworm",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                help_text="Current status of the interview",
                max_length=20,
                verbose_name="interview status",
            ),
        ),
    ]
