# Generated by Django 5.2.8 on 2025-11-30 17:26

import src.apps.shared.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={"unique": "A user with this email already exists."},
                        help_text="User's email address used for authentication",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "phone_number",
                    src.apps.shared.models.fields.PhoneNumberField(
                        blank=True, help_text="User's contact phone number", null=True, verbose_name="phone number"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("candidate", "Candidate"), ("employee", "Employee")],
                        default="candidate",
                        help_text="The user's type within the company",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "invitation_status",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("invited", "Invited")],
                        default="invited",
                        help_text="The invitation status of the contact",
                        max_length=20,
                        verbose_name="invitation status",
                    ),
                ),
                (
                    "has_confirmed_email",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the user has confirmed their email address",
                        verbose_name="has confirmed email",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-created_at"],
            },
        ),
    ]
