# Generated by Django 5.2.8 on 2025-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userorm_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorm",
            name="type",
            field=models.CharField(
                choices=[("candidate", "Candidate"), ("employer", "Employer")],
                default="candidate",
                help_text="The user's type within the company",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
