# Generated by Django 5.2.8 on 2025-12-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userorm_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userorm",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_employees", "Can view employee list"),
                    ("invite_employees", "Can invite new employees"),
                    ("manage_employees", "Can manage employees"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
