"""Django settings for src project.

Generated by 'django-admin startproject' using Django 5.2
"""

from pathlib import Path
from typing import Literal

from src.settings.environment import env


# ========================== BASE SETTINGS ==============================

BASE_DIR = Path(__file__).resolve().parent.parent

ENVIRONMENT: Literal["local", "prod"] = env("ISHFLOW_ENVIRONMENT")  # type: ignore

SECRET_KEY = env.str("ISHFLOW_SECRET_KEY")

DEBUG = env.bool("ISHFLOW_DEBUG", default=False)  # type: ignore

ALLOWED_HOSTS = env.list("ISHFLOW_ALLOWED_HOSTS", default=[])  # type: ignore

SITE_NAME = env.str("ISHFLOW_SITE_NAME", default="ISHFLOW")  # type: ignore

ROOT_URLCONF = "src.urls"

WSGI_APPLICATION = "src.wsgi.application"

DATABASES = {"default": env.db("ISHFLOW_DATABASE_URL")}

# =========================== APPLICATIONS definition ==============================
_THIRD_PARTY_APPS = [
    "rest_framework",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "axes",
    "corsheaders",
    "import_export",
    "cachalot",
]

# Add local environments dependencies
if ENVIRONMENT == "local":
    _THIRD_PARTY_APPS.append("django_extensions")

if DEBUG:
    _THIRD_PARTY_APPS.extend(
        [
            "debug_toolbar",
            "query_counter",
        ]
    )

_CUSTOM_APPS = [
    "src.apps.shared",
    "src.apps.accounts",
    "src.apps.companies",
    "src.apps.candidates",
    "src.apps.jobs",
    "src.apps.applications",
    "src.apps.notifications",
    "src.apps.interviews",
]

INSTALLED_APPS = [
    # Django unfold admin interface. Link: https://unfoldadmin.com/docs/installation/quickstart/
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    # Default Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    *_THIRD_PARTY_APPS,
    *_CUSTOM_APPS,
]

# Site ID for django.contrib.sites
SITE_ID = 1

# =========================== MIDDLEWARE definition ==============================
_THIRD_PARTY_MIDDLEWARE = [
    "axes.middleware.AxesMiddleware",
]

# Add debug toolbar middleware in local/dev environments
if DEBUG:
    _THIRD_PARTY_MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")
    _THIRD_PARTY_MIDDLEWARE.append("query_counter.middleware.DjangoQueryCounterMiddleware")

_CUSTOM_MIDDLEWARE = []

MIDDLEWARE = [
    # CorsMiddleware should be placed as high as possible
    "corsheaders.middleware.CorsMiddleware",
    # Default Django middleware
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise middleware should be right after SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    *_THIRD_PARTY_MIDDLEWARE,
    *_CUSTOM_MIDDLEWARE,
]

# ========================== AUTHENTICATION & SECURITY ==============================
# Custom User Model
AUTH_USER_MODEL = "accounts.UserORM"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = (
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
)

# Login URL configuration
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
CSRF_TRUSTED_ORIGINS = env.list("ISHFLOW_CSRF_TRUSTED_ORIGINS", default=[])  # type: ignore

# ========================== INTERNATIONALIZATION ==============================
LANGUAGE_CODE = "en-us"

TIME_ZONE = env.str("ISHFLOW_TIMEZONE", default="UTC")  # type: ignore

USE_I18N = True

USE_TZ = True

# ========================== STATIC FILES configuration ==============================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Static files (CSS, JavaScript, Images)
STATIC_ROOT = BASE_DIR.parent / "public" / "static"

STATICFILES_DIRS = [BASE_DIR.parent / "public" / "assets"]

# Storage configuration (overridden by storages.py)
STORAGES = {
    "default": {
        "BACKEND": "src.settings.contrib.storages.MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "src.settings.contrib.storages.StaticStorage",
    },
}
